routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\MaestroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

//Alumnos
Route::resource('alumnos', AlumnoController::class);

//Maestros
Route::resource('maestros', MaestroController::class);

app/Models/Alumno.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Alumno extends Model
{
    protected $fillable = [
        'nombre',
        'primer_apellido',
        'segundo_apellido',
        'sexo',
        'edad',
        'anio_escolar',
        'nombre_tutor',
        'telefono_tutor'
    ];
    public function maestro() {
        return $this->belongsToMany(Maestro::class)->withPivot('maestro_id', 'alumno_id')->withTimestamps();
    }
}

app/Http/Controllers/AlumnoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Alumno;
use App\Models\Maestro;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use DB;
use Alert;

class AlumnoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $alumnos = Alumno::get(['id','nombre','primer_apellido', 'segundo_apellido','sexo','edad','anio_escolar','nombre_tutor','telefono_tutor']);
        return view('alumnos.index')->with(compact('alumnos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $maestros = Maestro::get(['id','materia','nombre','primer_apellido']);
        return view('alumnos.create')->with(compact('maestros'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'nombre' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'primer_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'segundo_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'sexo' => 'required|alpha|max:1|min:1',
            'edad' => 'required|integer|between:3,20',
            'anio_escolar' => 'required|regex:/^[\pL\s\-]+$/u|max:20|min:3',
            'nombre_tutor' => 'required|regex:/^[\pL\s\-]+$/u|max:90|min:3',
            'telefono_tutor' => 'required|alpha_num|max:10|min:10'
        ]);
        if( $validator->fails() ) {
            alert()->error('¡Error!', $validator->messages()->all());
            return Redirect::back()->withInput();
        }
        DB::beginTransaction();
        try {
            $alumno = Alumno::create([
                'nombre' => mb_strtoupper($request->nombre),
                'primer_apellido' => mb_strtoupper($request->primer_apellido),
                'segundo_apellido' => mb_strtoupper($request->segundo_apellido),
                'sexo' => mb_strtoupper($request->sexo),
                'edad' => $request->edad,
                'anio_escolar' => mb_strtoupper($request->anio_escolar),
                'nombre_tutor' => mb_strtoupper($request->nombre_tutor),
                'telefono_tutor' => $request->telefono_tutor,
            ]);
            if($request->materia != "" || $request->materia != NULL){
                $alumno->maestro()->attach($request->materia);
            }
        } catch (\Exception $e) {
            alert()->error('¡Error al guardar!', $e->errorInfo[2]);
            DB::rollback();
            return Redirect::back()->withInput();
        }
        DB::commit();
        alert()->success('Alumno almacenado con éxito','Éxito al guardar');
        return redirect()->route('alumnos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Alumno  $alumno
     * @return \Illuminate\Http\Response
     */
    public function show(Alumno $alumno)
    {
        $alumno = Alumno::find($alumno->id);
        $maestros = Maestro::get(['id','materia','nombre','primer_apellido']);
        $asignados= array(); 
        for($i = 0; $i<$alumno->maestro->count(); $i++){
            $asignados[]=$alumno->maestro[$i]->id;
        }
        return view('alumnos.show')->with(compact('alumno','maestros','asignados'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Alumno  $alumno
     * @return \Illuminate\Http\Response
     */
    public function edit(Alumno $alumno)
    {
        $alumno = Alumno::find($alumno->id);
        $asignados= array(); 
        for($i = 0; $i<$alumno->maestro->count(); $i++){
            $asignados[]=$alumno->maestro[$i]->id;
        }
        // dd($asignados);
        $maestros = Maestro::get(['id','materia','nombre','primer_apellido']);
        return view('alumnos.edit')->with(compact('alumno','maestros','asignados'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Alumno  $alumno
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Alumno $alumno)
    {
        $validator = Validator::make($request->all(),[
            'nombre' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'primer_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'segundo_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'sexo' => 'required|alpha|max:1|min:1',
            'edad' => 'required|integer|between:3,20',
            'anio_escolar' => 'required|regex:/^[\pL\s\-]+$/u|max:20|min:3',
            'nombre_tutor' => 'required|regex:/^[\pL\s\-]+$/u|max:90|min:3',
            'telefono_tutor' => 'required|alpha_num|max:10|min:10'
        ]);
        if( $validator->fails() ) {
            alert()->error('¡Error!', $validator->messages()->all());
            return Redirect::back()->withInput();
        }
        DB::beginTransaction();
        try {
            $alumno = Alumno::find($alumno->id);
            $alumno->nombre = mb_strtoupper($request->nombre);
            $alumno->primer_apellido = mb_strtoupper($request->primer_apellido);
            $alumno->segundo_apellido = mb_strtoupper($request->segundo_apellido);
            $alumno->sexo = mb_strtoupper($request->sexo);
            $alumno->edad = $request->edad;
            $alumno->anio_escolar = mb_strtoupper($request->anio_escolar);
            $alumno->nombre_tutor = mb_strtoupper($request->nombre_tutor);
            $alumno->telefono_tutor = $request->telefono_tutor;
            $alumno->save();
            $alumno->maestro()->detach();
            if($request->materia != "" || $request->materia != NULL){
                foreach($request->materia as $materia){
                    $alumno->maestro()->attach($materia);
                }
            }
        } catch (\Exception $e) {
            dd($e);
            DB::rollback();
            alert()->error('¡Error al guardar!', $e->errorInfo[2]);
            return Redirect::back()->withInput();
        }
        DB::commit();
        alert()->success('Alumno actualizado con éxito','Éxito al guardar');
        return redirect()->route('alumnos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Alumno  $alumno
     * @return \Illuminate\Http\Response
     */
    public function destroy(Alumno $alumno)
    {
        DB::beginTransaction();
        try {
            $al = Alumno::find($alumno->id);
            $al->delete();
            $al->maestro()->detach($alumno->id);
        } catch (\Exception $e) {
            DB::rollback();
            alert()->error('¡Error al guardar!', $e->errorInfo[2]);
            return Redirect::back()->withInput();
        }
        DB::commit();
        alert()->success('Alumno eliminado con éxito');
        return redirect()->route('alumnos.index');
    }
}

resources/views/alumnos/create.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Crear alumno</h1>
    </div>
@stop

@section('content')
<div class="container">
    <form method="post" action="{{ route('alumnos.store') }}">
        @csrf
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control text-uppercase" name="nombre" id="nombre" placeholder="Nombre" maxlength="30" required value="{{ old('nombre') }}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="primer_apellido">Primer apellido:</label>
                <input type="text" class="form-control text-uppercase" name="primer_apellido" id="primer_apellido" placeholder="Primer apellido" maxlength="30" required value="{{ old('primer_apellido') }}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="segundo_apellido">Segundo apellido:</label>
                <input type="text" class="form-control text-uppercase" name="segundo_apellido" id="segundo_apellido" placeholder="Segundo apellido" maxlength="30" required value="{{ old('segundo_apellido') }}" autocomplete="off">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="sexo">Sexo:</label>
                <select class="selectpicker form-control text-uppercase" aria-label="Default select example" name="sexo" id="sexo" required value="{{ old('sexo') }}">
                    <option selected>Selecciona uno</option>
                    <option value="F">Femenino</option>
                    <option value="M">Masculino</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="edad">Edad:</label>
                <input type="text" name="edad" id="edad" class="form-control text-uppercase" maxlength="2" placeholder="Edad" required value="{{ old('edad') }}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="anio_escolar">Año escolar:</label>
                <input type="text" name="anio_escolar" id="anio_escolar" class="form-control text-uppercase" maxlength="20" placeholder="Ejem: Primero, Segundo" required value="{{ old('anio_escolar') }}" autocomplete="off">
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4">
                <label for="nombre_tutor">Nombre tutor:</label>
                <input type="text" name="nombre_tutor" id="nombre_tutor" class="form-control text-uppercase" maxlength="90" placeholder="Nombre tutor" required value="{{ old('nombre_tutor') }}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="telefono_tutor">Teléfono tutor:</label>
                <input type="text" name="telefono_tutor" id="telefono_tutor" class="form-control text-uppercase" maxlength="10" placeholder="Teléfono tutor" required value="{{ old('telefono_tutor') }}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="materia">Materia:</label>
                <select class="selectpicker form-control text-uppercase" multiple name="materia[]" id="materia" placeholder="SELECCIONE UNA">
                    @foreach($maestros as $maestro)
                        <option value="{{$maestro->id}}">{{$maestro->materia}}-{{$maestro->nombre}} {{$maestro->primer_apellido}}
                    @endforeach
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-11">
                <input type="submit" class="btn btn-primary float-right" value="Guardar">
            </div>
            <div class="col-1">
                <a class="btn btn-danger float-end" href="{{route('alumnos.index')}}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
@include('sweetalert::alert')
@stop

@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@stop

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

@stop

resources/views/alumnos/edit.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Editar alumno</h1>
    </div>
@stop

@section('content')

<div class="container">
    <form method="post" action="{{route('alumnos.update', ['alumno' => $alumno->id])}}">
        @csrf
        @method('PUT')
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control text-uppercase" name="nombre" id="nombre" placeholder="Nombre" maxlength="30" value="{{$alumno->nombre}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="primer_apellido">Primer apellido:</label>
                <input type="text" class="form-control text-uppercase" name="primer_apellido" id="primer_apellido" placeholder="Primer apellido" maxlength="30" value="{{$alumno->primer_apellido}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="segundo_apellido">Segundo apellido:</label>
                <input type="text" class="form-control text-uppercase" name="segundo_apellido" id="segundo_apellido" placeholder="Segundo apellido" maxlength="30" value="{{$alumno->segundo_apellido}}" autocomplete="off">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="sexo">Sexo:</label>
                <select class="selectpicker form-control text-uppercase" name="sexo" id="sexo">
                    <option value="F" @if($alumno->sexo == 'F') selected @endif>Femenino</option>
                    <option value="M" @if($alumno->sexo == 'M') selected @endif>Masculino</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="edad">Edad:</label>
                <input type="text" name="edad" id="edad" class="form-control text-uppercase" maxlength="2" value="{{$alumno->edad}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="anio_escolar">Año escolar:</label>
                <input type="text" name="anio_escolar" id="anio_escolar" class="form-control text-uppercase" maxlength="20" value="{{$alumno->anio_escolar}}" autocomplete="off">
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4">
                <label for="nombre_tutor">Nombre tutor:</label>
                <input type="text" name="nombre_tutor" id="nombre_tutor" class="form-control text-uppercase" maxlength="90" value="{{$alumno->nombre_tutor}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="telefono_tutor">Teléfono tutor:</label>
                <input type="text" name="telefono_tutor" id="telefono_tutor" class="form-control text-uppercase" maxlength="10" value="{{$alumno->telefono_tutor}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="materia">Materia:</label>
                <select class="selectpicker form-control text-uppercase" multiple name="materia[]" id="materia" placeholder="SELECCIONE UNA MATERIA">
                    @foreach($maestros as $maestro)
                        <option value="{{$maestro->id}}" @if(in_array($maestro->id, $asignados)) selected @endif>{{$maestro->materia}}-{{$maestro->nombre}} {{$maestro->primer_apellido}}
                    @endforeach
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-11">
                <input type="submit" class="btn btn-primary float-right" value="Guardar">
            </div>
            <div class="col-1">
                <a class="btn btn-danger float-end" href="{{route('alumnos.index')}}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
@include('sweetalert::alert')
@stop
@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@stop

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

@stop

resources/views/alumnos/index.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Mostrar alumnos</h1>
    </div>
@stop

@section('content')
    <div class="row mb-2">
        <div class="col-md-12">
                <a class="btn btn-primary float-end" href="{{route('alumnos.create')}}">Nuevo alumno</a>
        </div>
    </div>
    <table class="table table-dark table-striped">
        <tr>
            <th>Nombre</th>
            <th>Sexo</th>
            <th>Edad</th>
            <th>Año escolar</th>
            <th>Nombre tutor</th>
            <th>Teléfono tutor</th>
            <!-- <th>Materia</th> -->
            <th colspan=3>Acción</th>
        </tr> 
        @foreach($alumnos as $alumno)
            <tr>
                <td>{{$alumno->nombre}} {{$alumno->primer_apellido}} {{$alumno->segundo_apellido}}</td>
                <td>{{$alumno->sexo}}</td>
                <td>{{$alumno->edad}}</td>
                <td>{{$alumno->anio_escolar}}</td>
                <td>{{$alumno->nombre_tutor}}</td>
                <td>{{$alumno->telefono_tutor}}</td>
                <td>
                    <a href="{{url('/alumnos/'.$alumno->id.'/edit')}}" class="btn btn-primary"><i class="fas fa-solid fa-pen" title="Editar"></i></a>
                </td>
                <td>
                    <a href="{{route('alumnos.show', $alumno->id)}}" class="btn btn-primary"><i class="fas fa-solid fa-eye" title="Mostrar"></i></a>
                </td>
                <td>
                    <form method="post" action="{{route('alumnos.destroy', $alumno)}}" id="formDestroy{{$alumno->id}}" onsubmit="borrar(event)">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-primary"><i class="fas fa-solid fa-ban" title="Eliminar"></i></button>
                    </form>
                </td>
            </tr>   
        @endforeach
    </table>
    @include('sweetalert::alert')
@stop

@section('js')
<script type="text/javascript" src="/js/app.js"></script>

<script>
    function borrar(e){
        let formD = e.target.id
        e.preventDefault();
        Swal.fire({
            title: '¿Está seguro que desea borrar al alumno?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: '¡Sí, borrar!',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                document.forms[formD].submit();
            }
        })
    }
</script>
@stop

resources/views/alumnos/show.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Mostrar alumno</h1>
    </div>
@stop

@section('content')

<div class="container">
    <div class="row mb-3">
        <div class="col-md-4">
            <label for="nombre">Nombre:</label>
            <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombre" maxlength="30" value="{{$alumno->nombre}}" readonly>
        </div>
        <div class="col-md-4">
            <label for="primer_apellido">Primer apellido:</label>
            <input type="text" class="form-control" name="primer_apellido" id="primer_apellido" placeholder="Primer apellido" maxlength="30" value="{{$alumno->primer_apellido}}" readonly>
        </div>
        <div class="col-md-4">
            <label for="segundo_apellido">Segundo apellido:</label>
            <input type="text" class="form-control" name="segundo_apellido" id="segundo_apellido" placeholder="Segundo apellido" maxlength="30" value="{{$alumno->segundo_apellido}}" readonly>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-4">
            <label for="sexo">Sexo:</label>
            <select class="form-select" aria-label="Default select example" name="sexo" id="sexo" disabled>
                <option value="F" @if($alumno->sexo == 'F') selected @endif>Femenino</option>
                <option value="M" @if($alumno->sexo == 'M') selected @endif>Masculino</option>
            </select>
        </div>
        <div class="col-md-4">
            <label for="edad">Edad:</label>
            <input type="text" name="edad" id="edad" class="form-control" maxlength="2" value="{{$alumno->edad}}" readonly>
        </div>
        <div class="col-md-4">
            <label for="anio_escolar">Año escolar:</label>
            <input type="text" name="anio_escolar" id="anio_escolar" class="form-control" maxlength="2" value="{{$alumno->anio_escolar}}" readonly>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-md-4">
            <label for="nombre_tutor">Nombre tutor:</label>
            <input type="text" name="nombre_tutor" id="nombre_tutor" class="form-control" maxlength="90" value="{{$alumno->nombre_tutor}}" readonly>
        </div>
        <div class="col-md-4">
            <label for="telefono_tutor">Teléfono tutor:</label>
            <input type="text" name="telefono_tutor" id="telefono_tutor" class="form-control" maxlength="10" value="{{$alumno->telefono_tutor}}" readonly>
        </div>
        <div class="col-md-4">
            <label for="materia">Materia:</label>
            <select class="form-select" aria-label="Default select example" name="materia" id="materia" disabled>
                <option selected>SIN ASIGNAR</option>
                @foreach($maestros as $maestro)
                    <option value="{{$maestro->id}}" @if(in_array($maestro->id, $asignados)) selected @endif>{{$maestro->materia}}-{{$maestro->nombre}} {{$maestro->primer_apellido}}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-danger float-end" href="{{route('alumnos.index')}}">Regresar</a>
        </div>
    </div>
</div>

@stop