routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\MaestroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

//Alumnos
Route::resource('alumnos', AlumnoController::class);

//Maestros
Route::resource('maestros', MaestroController::class);

app/Models/Maestro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Maestro extends Model
{
    protected $fillable = [
        'nombre',
        'primer_apellido',
        'segundo_apellido',
        'sexo',
        'edad',
        'materia'
    ];

    public function alumno() {
        return $this->belongsToMany(Alumno::class)->withPivot('maestro_id', 'alumno_id');
    }
}

app/Http/Controllers/MaestroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Maestro;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use DB;
use Alert;

class MaestroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $maestros = Maestro::get(['id','nombre','primer_apellido', 'segundo_apellido', 'sexo', 'edad','materia']);
        return view('maestros.index')->with(compact('maestros'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('maestros.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'nombre' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'primer_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'segundo_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'sexo' => 'required|alpha|max:1|min:1',
            'edad' => 'required|integer|between:20,65',
            'materia' => 'required|regex:/^[\pL\s\-]+$/u|max:20|min:3',
        ]);
        if( $validator->fails() ) {
            alert()->error('¡Error!', $validator->messages()->all());
            return Redirect::back()->withInput();
        }
        DB::beginTransaction();
        try {
            $maestro = Maestro::create([
                'nombre' => mb_strtoupper($request->nombre),
                'primer_apellido' => mb_strtoupper($request->primer_apellido),
                'segundo_apellido' => mb_strtoupper($request->segundo_apellido),
                'sexo' => mb_strtoupper($request->sexo),
                'edad' => $request->edad,
                'materia' => mb_strtoupper($request->materia)
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            alert()->error('¡Error al guardar!', $e->errorInfo[2]);
            return Redirect::back()->withInput();
        }
        DB::commit();
        alert()->success('Maestro actualizado con éxito','Éxito al guardar');
        return redirect()->route('maestros.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Maestro  $maestro
     * @return \Illuminate\Http\Response
     */
    public function show(Maestro $maestro)
    {
        $maestro = Maestro::find($maestro->id);
        return view('maestros.show')->with(compact('maestro'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Maestro  $maestro
     * @return \Illuminate\Http\Response
     */
    public function edit(Maestro $maestro)
    {
        $maestro = Maestro::find($maestro->id);
        return view('maestros.edit')->with(compact('maestro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Maestro  $maestro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Maestro $maestro)
    {
        $validator = Validator::make($request->all(),[
            'nombre' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'primer_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'segundo_apellido' => 'required|regex:/^[\pL\s\-]+$/u|max:30|min:3',
            'sexo' => 'required|alpha|max:1|min:1',
            'edad' => 'required|integer|between:20,65',
            'materia' => 'required|regex:/^[\pL\s\-]+$/u|max:20|min:3',
        ]);
        if( $validator->fails() ) {
            alert()->error('¡Error!', $validator->messages()->all());
            return Redirect::back()->withInput();
        }
        DB::beginTransaction();
        try {
            $maestro = Maestro::find($maestro->id);
            $maestro->nombre = mb_strtoupper($request->nombre);
            $maestro->primer_apellido = mb_strtoupper($request->primer_apellido);
            $maestro->segundo_apellido = mb_strtoupper($request->segundo_apellido);
            $maestro->sexo = mb_strtoupper($request->sexo);
            $maestro->edad = $request->edad;
            $maestro->materia = mb_strtoupper($request->materia);
            $maestro->save();
        } catch (\Exception $e) {
        DB::rollback();
        alert()->error('¡Error al guardar!', $e->errorInfo[2]);
        return Redirect::back()->withInput();
    }
    DB::commit();
    alert()->success('Maestro actualizado con éxito','Éxito al guardar');
    return redirect()->route('maestros.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Maestro  $maestro
     * @return \Illuminate\Http\Response
     */
    public function destroy(Maestro $maestro)
    {
        DB::beginTransaction();
        try {
            $ma = Maestro::find($maestro->id);
            $ma->delete();
            $ma->alumno()->detach($maestro->id);
        } catch (\Exception $e) {
            DB::rollback();
            alert()->error('¡Error al guardar!', $e->errorInfo[2]);
            return Redirect::back()->withInput();
        }
        DB::commit();
        alert()->success('Maestro eliminado con éxito');
        return redirect()->route('maestros.index');
    }
}

resources/views/maestros/create.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Crear maestro</h1>
    </div>
@stop

@section('content')

<div class="container">
    <form method="post" action="{{route('maestros.store')}}">
        @csrf
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control text-uppercase" name="nombre" id="nombre" placeholder="Nombre" maxlength="30" required value="{{ old('nombre') }}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="primer_apellido">Primer apellido:</label>
                <input type="text" class="form-control text-uppercase" name="primer_apellido" id="primer_apellido" placeholder="Primer apellido" maxlength="30" required value="{{ old('primer_apellido') }}" autocomplete="off" >
            </div>
            <div class="col-md-4">
                <label for="segundo_apellido">Segundo apellido:</label>
                <input type="text" class="form-control text-uppercase" name="segundo_apellido" id="segundo_apellido" placeholder="Segundo apellido" maxlength="30" required value="{{ old('segundo_apellido') }}" autocomplete="off">
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4">
                <label for="sexo">Sexo:</label>
                <select class="form-select text-uppercase" aria-label="Default select example" name="sexo" id="sexo" required value="{{ old('sexo') }}">
                    <option selected>Selecciona uno</option>
                    <option value="F">Femenino</option>
                    <option value="M">Masculino</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="edad">Edad:</label>
                <input type="text" name="edad" id="edad" class="form-control text-uppercase" maxlength="2" required value="{{ old('edad') }}" placeholder="Edad" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="materia">Materia:</label>
                <input type="text" name="materia" id="materia" class="form-control text-uppercase" maxlength="20" required value="{{ old('materia') }}" placeholder="Materia" autocomplete="off">
            </div>
        </div>
        <div class="row">
            <div class="col-11">
                <input type="submit" class="btn btn-primary float-end" value="Guardar">
            </div>
            <div class="col-1">
                <a class="btn btn-danger float-end" href="{{route('maestros.index')}}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
@include('sweetalert::alert')

@stop

@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@stop

resources/views/maestros/edit.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Editar maestro</h1>
    </div>
@stop

@section('content')

<div class="container">
    <form method="post" action="{{route('maestros.update', ['maestro' => $maestro->id])}}">
        @csrf
        @method('put')
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control text-uppercase" name="nombre" id="nombre" placeholder="Nombre" maxlength="30" value="{{$maestro->nombre}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="primer_apellido">Primer apellido:</label>
                <input type="text" class="form-control text-uppercase" name="primer_apellido" id="primer_apellido" placeholder="Primer apellido" maxlength="30"value="{{$maestro->primer_apellido}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="segundo_apellido">Segundo apellido:</label>
                <input type="text" class="form-control text-uppercase" name="segundo_apellido" id="segundo_apellido" placeholder="Segundo apellido" maxlength="30" value="{{$maestro->segundo_apellido}}" autocomplete="off">
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4">
                <label for="sexo">Sexo:</label>
                <select class="form-select text-uppercase" aria-label="Default select example" name="sexo" id="sexo">
                    <option value="F" @if($maestro->sexo == 'F') selected @endif>Femenino</option>
                    <option value="M" @if($maestro->sexo == 'M') selected @endif>Masculino</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="edad">Edad:</label>
                <input type="text" name="edad" id="edad" class="form-control text-uppercase" maxlength="2" value="{{$maestro->edad}}" autocomplete="off">
            </div>
            <div class="col-md-4">
                <label for="materia">Materia:</label>
                <input type="text" name="materia" id="materia" class="form-control text-uppercase" maxlength="20" value="{{$maestro->materia}}" autocomplete="off">
            </div>
        </div>
        <div class="row">
            <div class="col-11">
                <input type="submit" class="btn btn-primary float-end" value="Guardar">
            </div>
            <div class="col-1">
                <a class="btn btn-danger float-end" href="{{route('maestros.index')}}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
@include('sweetalert::alert')
@stop

resources/views/maestros/index.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Mostrar maestros</h1>
    </div>
@stop

@section('content')
    <div class="row mb-2">
        <div class="col-md-12">
                <a class="btn btn-primary float-end" href="{{route('maestros.create')}}">Nuevo maestro</a>
        </div>
    </div>
    <table class="table table-dark table-striped">
        <tr>
            <th>Nombre</th>
            <th>Sexo</th>
            <th>Edad</th>
            <th>Materia</th>
            <th colspan="3">Acción</th>
        </tr> 
            @foreach($maestros as $maestro)
            <tr>
                <td>{{$maestro->nombre}} {{$maestro->primer_apellido}} {{$maestro->segundo_apellido}}</td>
                <td>{{$maestro->sexo}}</td>
                <td>{{$maestro->edad}}</td>
                <td>{{$maestro->materia}}</td>
                <td>
                    <a href="{{url('/maestros/'.$maestro->id.'/edit')}}" class="btn btn-primary"><i class="fas fa-solid fa-pen" title="Editar"></i></a>
                </td>
                <td>
                    <a href="{{route('maestros.show', $maestro->id)}}" class="btn btn-primary"><i class="fas fa-solid fa-eye" title="Mostrar"></i></a>
                </td>
                <td>
                    <form method="post" action="{{route('maestros.destroy', $maestro->id)}}" id="formDestroy{{$maestro->id}}" onsubmit="borrar(event)">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-primary"><i class="fas fa-solid fa-ban" title="Eliminar"></i></button>
                    </form>
                </td>
            </tr>   
            @endforeach
    </table>
    @include('sweetalert::alert')

@stop

@section('js')
<script type="text/javascript" src="/js/app.js"></script>

<script>
    function borrar(e){
        let formD = e.target.id
        e.preventDefault();
        Swal.fire({
            title: '¿Está seguro que desea borrar al maestro?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: '¡Sí, borrar!',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                document.forms[formD].submit();
            }
        })
    }
</script>
@stop

resources/views/maestros/show.blade.php
@extends('home')

@section('content_header')
    <div class="container">
        <h1>Mostrar maestro</h1>
    </div>
@stop

@section('content')

<div class="container">
    <form method="post" action="{{route('maestros.update', ['maestro' => $maestro->id])}}">
        @csrf
        @method('put')
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombre" maxlength="30" value="{{$maestro->nombre}}" readonly>
            </div>
            <div class="col-md-4">
                <label for="primer_apellido">Primer apellido:</label>
                <input type="text" class="form-control" name="primer_apellido" id="primer_apellido" placeholder="Primer apellido" maxlength="30"value="{{$maestro->primer_apellido}}" readonly>
            </div>
            <div class="col-md-4">
                <label for="segundo_apellido">Segundo apellido:</label>
                <input type="text" class="form-control" name="segundo_apellido" id="segundo_apellido" placeholder="Segundo apellido" maxlength="30" value="{{$maestro->segundo_apellido}}" readonly>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-4">
                <label for="sexo">Sexo:</label>
                <select class="form-select" aria-label="Default select example" name="sexo" id="sexo" disabled>
                    <option value="F" @if($maestro->sexo == 'F') selected @endif>Femenino</option>
                    <option value="M" @if($maestro->sexo == 'M') selected @endif>Masculino</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="edad">Edad:</label>
                <input type="text" name="edad" id="edad" class="form-control" maxlength="2" value="{{$maestro->edad}}" readonly>
            </div>
            <div class="col-md-4">
                <label for="materia">Materia:</label>
                <input type="text" name="materia" id="materia" class="form-control" maxlength="20" value="{{$maestro->materia}}" readonly>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-danger float-end" href="{{route('maestros.index')}}">Regresar</a>
            </div>
        </div>
    </form>
</div>
@include('sweetalert::alert')
@stop